name: build-and-deploy
run-name: ${{ github.actor }} is building and deploying
on:
  push:
    branches:
    - gh-pages
jobs:
  Build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run deploy
        